pushing new ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -50,8 +50,8 @@ jobs:
     #   working-directory: ./frontend
     #   run: |
     #     df -h
-    #     sudo rm -rf ./build
     #     yarn install
+    #     sudo rm -rf ./build
     #     yarn run build
 
     # Run backend tests
@@ -69,7 +69,12 @@ jobs:
         cd ./backend
         touch .env
         echo "${{ secrets.PROD }}" > .env
+    - name: Stop and Start PM2 Processes (if any)
+      run: |
+        pm2 list || true  # Check if any processes are running (won't fail)
+        pm2 stop all || true  # Stop all PM2 processes, ignore errors if no processes are found
+        pm2 start all || true  # Start all PM2 processes, ignore errors if no processes are found
 
-    - run: pm2 start all
+    # - run: pm2 start all
 
-    - run: pm2 restart all
+    # - run: pm2 restart all
